title: West Midlands
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: /
params:
  disableDarkMode: true
  shortDateFormat: '15:04 — Jan 2'
  down: '#e60000'
  systems:
    - name: Game
      category: Systems
      description: The West Midlands game
    - name: Discord
      category: Systems
      description: Our chat server.
  dateFormat: 'January 2, 2006 at 3:04 PM'
  brand: '#0a0c0f'
  headerTextColor: white
  logo: /img/avatar.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: '#cc4400'
  notice: '#24478f'
  incidentHistoryFormat: monthly
  ok: '#008000'
  categories:
    - name: Systems
      closed: true
  description: 'West Midlands'' Status Page, any downtime or updates will be posted here.'
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
